export const BookingActionTypes = {
  SET_SPECIALIST: "SET_SPECIALIST",
  ADD_CART_ITEM: "ADD_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
  SELECT_FACILITY: "SELECT_FACILITY",
  SET_MEETING_TIME: "SET_MEETING_TIME",
};
