export const BookingActionTypes = {
  SET_SPECIALIST: "SET_SPECIALIST",
  TOGGLE_CART_ACTION: "TOGGLE_CART_ACTION",
  ADD_CART_ITEM: "ADD_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
  SET_SHOW_CART: "SET_SHOW_CART",
  SELECT_FACILITY: "SELECT_FACILITY",
};
